Back/Models/Contexts/IdentityContext.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace Tetris.Models.Contexts
{
    public class IdentityContext : IdentityDbContext<TetrisUser>
    {
        public IdentityContext(DbContextOptions<IdentityContext> options) : base(options) { }
    }
}

Back/Models/DbMigrate.cs
using Microsoft.AspNetCore.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.Extensions.DependencyInjection;
using Tetris.Models.Contexts;

namespace Tetris.Models
{
    public static class DbMigrate
    {
        public static void EnsureCreated(IApplicationBuilder app)
        {
            var context = app.ApplicationServices
                .CreateScope().ServiceProvider
                .GetRequiredService<IdentityContext>();
            if(context.Database.GetPendingMigrations().Any())
            {
                context.Database.Migrate();
            }

        }
    }
}

Back/Models/Forms/LoginForm.cs
using System.ComponentModel.DataAnnotations;

namespace Tetris.Models.Forms
{
    public class LoginForm
    {
        [Required(ErrorMessage = "Не указано имя"), MinLength(5, ErrorMessage = "Имя минимум 5 символов")]
        public string Username { get; set; }
        
        [Required(ErrorMessage = "Не указан пароль"), MinLength(5, ErrorMessage = "Пароль минимум 5 символов")]
        public string Password { get; set; }
    }
}

Back/Models/IdentityContext.cs
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace Tetris.Models
{
    public class IdentityContext : IdentityDbContext
    {
        public IdentityContext(DbContextOptions<IdentityContext> options) : base(options) { }
    }
}

Back/Models/TetrisUser.cs
using Microsoft.AspNetCore.Identity;

namespace Tetris.Models
{
    public class TetrisUser : IdentityUser
    {
        public string Settings { get; set; }
    }
}

Back/Components/FieldViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Tetris.Components
{
    public class FieldViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Back/Views/Home/Game.cshtml
@{
    Layout = "_Layout";
}
@if(ViewContext.HttpContext.User.Identity.IsAuthenticated)
{
    @await Component.InvokeAsync("Field")
}
else
{
    <div class="welcome">
        <h1>Добро пожаловать</h1>
        <span>Чтобы играть - <a asp-controller="Account" asp-action="Login">войдите</a> или <a asp-controller="Account" asp-action="Create">зарегистрируйтесь</a></span>
    </div>
}

Back/Views/Home/Index.cshtml
@{
    Layout = "_Layout";
}
@if(ViewContext.HttpContext.User.Identity.IsAuthenticated)
{
    
}
else
{
    <div class="welcome">
        <h1>Добро пожаловать</h1>
        <span>Чтобы играть - <a asp-controller="Account" asp-action="Login">войдите</a> или <a asp-controller="Account" asp-action="Create">зарегистрируйтесь</a></span>
    </div>
}

Back/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/styles.css">
    <script
        src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous">
    </script>
    <script src="~/js/field.js"></script>
    <script src="~/js/game.js"></script>
    <title>Тетрис</title>
</head>
<body>
    <header>
        <div class="container">
            <div class="flex header_container">
                <div class="logo">
                    <a href="/">Тетрис</a>  
                </div>
                <div class="login_buttons">
                    @if(ViewContext.HttpContext.User.Identity.IsAuthenticated)
                    {
                        <a class="logout button" asp-controller="Account" asp-action="Logout"><span>Выйти</span></a>
                    }
                    else
                    {
                        <a class="login button" asp-controller="Account" asp-action="Login" ><span>Войти</span></a>
                        <a class="register button" asp-controller="Account" asp-action="Create"><span>Зарегистрироваться</span></a>
                    }
                </div>
            </div>
        </div>
    </header>
    <main>
        <div class="container">
            @RenderBody()
        </div>
    </main>
</body>
</html>